services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - pokemon_data:/var/lib/postgresql/data

volumes:
  pokemon_data:
